spring:
  application:
    name: ym-payment
  profiles:
    active: dev
  #数据源配置
  datasource:
    url: jdbc:mysql://ymbok.com:3306/ym_payment?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ym_payment
    password: cH74ZTdsDsTjt8Kn
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8090

## Mybatis 配置
mybatis:
  type-aliases-package: com.ym.payment.domain
  mapper-locations: classpath:com/ym/payment/dao/*.xml
  configuration:
    map-underscore-to-camel-case: true


#eureka.client.service-url.defaultzone:http://localhost:8761/eureka/
#eureka.instance.leaseRenewalIntervalInSeconds:30


#日志监测路径
logging:
  level:
    com.ym.payment: debug
    org.springframework: debug

  #日志存储路径
  path: ./logs/
  #文件名
  file: ym_payment_
